90314 update dependencies
IntershopCommunicationsAG/test-gradle-plugin pull request #21
Opened 2023-10-24 13:29 UTC by cortlepp-intershop

# Changes

- update gradle wrapper to 8.4
- update dependencies
- update Java version to 17 LTS
- use the same build/release configuration for all gradle plugins from [the new .github repo](https://github.com/IntershopCommunicationsAG/.github)

2023-10-24 13:41 UTC, m-raab approved these changes

2023-10-24 14:15 UTC, DevDavido approved these changes

2023-10-25 05:07 UTC, skiesewetter-intershop approved these changes

2023-10-25 05:57 UTC, cortlepp-intershop commented
Do I need to update the version in `build.gradle.kts` before merging this PR? And if so, is this a major change? So `5.0.0`?

2023-10-25 06:56 UTC, DevDavido commented
Since this PR drops support for < Java 17, it's a breaking change as the published artifacts are compiled for at least JRE version 17. Therefore, please publish a new major version `5.0.0` then.

The version string needs to be adapted in the `build.gradle.kts` and in the `README.asciidoc` (see `latestRevision`). Also please revise the documentation regarding the supported Gradle version.

2023-12-06 10:01 UTC, DevDavido requested changes

2023-12-06 10:01 UTC, DevDavido commented on build.gradle.kts
> +        systemProperty("intershop.gradle.versions", "8.4,8.5")
May update the README too regarding the Gradle version(s)

2023-12-06 11:54 UTC, skiesewetter-intershop commented on build.gradle.kts
>      implementation("junit:junit:4.13.2")
Spock only supports JUnit4 as far as I know.

2023-12-06 12:33 UTC, DevDavido approved these changes

2023-12-06 12:36 UTC, merged